/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface AdminStatsResponseDto {
    /** Total users */
    totalUsers: number;
    /** Total matches */
    totalMatches: number;
    /** Pending reports */
    pendingReports: number;
}
