/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { AdminUserItemDto } from './adminUserItemDto';

export interface AdminUsersListResponseDto {
  /** List of users */
  data: AdminUserItemDto[];
  /** Total matching users */
  total: number;
  /** Number of skipped users */
  skip: number;
  /** Number of users requested */
  take: number;
}
