/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type AdminControllerGetUsersSortOrder = typeof AdminControllerGetUsersSortOrder[keyof typeof AdminControllerGetUsersSortOrder];


export const AdminControllerGetUsersSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
