/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type AdminControllerGetUsersParams = {
/**
 * Page number for pagination (default: 1)
 * @minimum 1
 */
page?: number;
/**
 * Number of users to return per page (default: 50)
 * @minimum 1
 * @maximum 50
 */
limit?: number;
/**
 * Search term to filter users by name or email
 */
search?: string;
/**
 * Filter users by banned status
 */
isBanned?: boolean;
};
