/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { AdminUserItemDtoFaculty } from './adminUserItemDtoFaculty';
import type { AdminUserItemDtoGender } from './adminUserItemDtoGender';

export interface AdminUserItemDto {
    /** User ID */
    id: string;
    /** User email */
    email: string;
    /** User name */
    name: string;
    /** User faculty */
    faculty: AdminUserItemDtoFaculty;
    /** User gender */
    gender: AdminUserItemDtoGender;
    /** Whether the user is banned */
    isBanned: boolean;
    /** Whether the user is an admin */
    isAdmin: boolean;
    /** User creation timestamp */
    createdAt: string;
}
