/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface AnnouncementDetailDto {
  /** Announcement ID */
  id: string;
  /** Announcement title */
  title: string;
  /** Announcement body */
  body: string;
  /** Number of users who received this announcement */
  recipientCount: number;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}
