/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { AnnouncementItemDto } from './announcementItemDto';

export interface AnnouncementsListResponseDto {
  /** List of announcements */
  data: AnnouncementItemDto[];
  /** Total announcements */
  total: number;
  /** Current page */
  page: number;
  /** Items per page */
  limit: number;
}
