/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { AuditLogItemDto } from './auditLogItemDto';

export interface AuditLogsResponseDto {
    /** Total audit logs */
    total: number;
    /** Current page number */
    page: number;
    /** Items per page */
    limit: number;
    /** Audit logs */
    logs: AuditLogItemDto[];
}
