/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { AuditLogItemDtoMetadata } from './auditLogItemDtoMetadata';
import type { AuditLogProfileDto } from './auditLogProfileDto';

export interface AuditLogItemDto {
  /** Audit log ID */
  id: string;
  /** Audit action */
  action: string;
  /** Actor user ID */
  actorId: string;
  /**
     * Target user ID
     * @nullable
     */
  targetId: string | null;
  /**
     * Additional audit metadata
     * @nullable
     */
  metadata: AuditLogItemDtoMetadata;
  /** Audit timestamp */
  timestamp: string;
  /** Actor profile */
  actor: AuditLogProfileDto;
  /** Target profile */
  target: AuditLogProfileDto | null;
}
