/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface BannedUserItemDto {
    /** User ID */
    id: string;
    /** User email */
    email: string;
    /** User name */
    name: string;
    /** Indicates if the user is banned */
    isBanned: boolean;
}
