/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { BannedUserItemDto } from './bannedUserItemDto';

export interface BanSucessResponseDto {
  /** User banned successfully */
  message: string;
  /** Details of the affected user */
  user: BannedUserItemDto;
}
