/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { BlockItemDto } from './blockItemDto';

export interface BlocksListResponseDto {
    /** List of blocked users */
    blocks: BlockItemDto[];
    /**
     * Cursor for pagination (null if no more blocked users)
     * @nullable
     */
    nextCursor: string | null;
}
