/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface BlockUserDto {
  /** ID of the user to block */
  blockedId: string;
  /** Optional reason for blocking */
  reason?: string;
}
