/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type ChatControllerGetShoutoutsType = (typeof ChatControllerGetShoutoutsType)[keyof typeof ChatControllerGetShoutoutsType];

export const ChatControllerGetShoutoutsType = {
    sent: 'sent',
    received: 'received'
} as const;
