/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { ConversationItemDto } from './conversationItemDto';

export interface ConversationsListResponseDto {
  conversations: ConversationItemDto[];
  /**
     * Cursor for pagination (null if no more conversations)
     * @nullable
     */
  nextCursor: string | null;
}
