/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { UserPreviewDto } from './userPreviewDto';

export interface ConversationDetailsResponseDto {
    id: string;
    participant: UserPreviewDto;
    isOnline: boolean;
    /** @nullable */
    lastOnline: string | null;
    createdAt: string;
    updatedAt: string;
}
