/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { CreateReportDtoReason } from './createReportDtoReason';

export interface CreateReportDto {
  /** ID of the user being reported */
  reportedId: string;
  /** Reason for reporting the user */
  reason: CreateReportDtoReason;
  /**
     * Additional details about the report
     * @maxLength 1000
     */
  description?: string;
}
