/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Type of swipe action
 */
export type CreateSwipeDtoType = typeof CreateSwipeDtoType[keyof typeof CreateSwipeDtoType];


export const CreateSwipeDtoType = {
  LIKE: 'LIKE',
  DISLIKE: 'DISLIKE',
} as const;
