/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Reason for reporting the user
 */
export type CreateReportDtoReason = (typeof CreateReportDtoReason)[keyof typeof CreateReportDtoReason];

export const CreateReportDtoReason = {
    INAPPROPRIATE_BEHAVIOR: 'INAPPROPRIATE_BEHAVIOR',
    FAKE_PROFILE: 'FAKE_PROFILE',
    SCAM: 'SCAM',
    HARASSMENT: 'HARASSMENT',
    OTHER: 'OTHER'
} as const;
