/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { CreateSwipeDtoType } from './createSwipeDtoType';

export interface CreateSwipeDto {
  /** ID of the user being swiped */
  receiverId: string;
  /** Type of swipe action */
  type: CreateSwipeDtoType;
}
