/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { DiscoveryUserItemDto } from './discoveryUserItemDto';

export interface DiscoveryListResponseDto {
  /** List of discovered users */
  users: DiscoveryUserItemDto[];
  /**
     * Cursor for pagination (null if no more users)
     * @nullable
     */
  nextCursor: string | null;
}
