/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { DiscoveryUserItemDtoFaculty } from './discoveryUserItemDtoFaculty';
import type { DiscoveryUserItemDtoInterestsItem } from './discoveryUserItemDtoInterestsItem';
import type { DiscoveryUserItemDtoLookingFor } from './discoveryUserItemDtoLookingFor';
import type { DiscoveryUserItemDtoNationality } from './discoveryUserItemDtoNationality';
import type { GalleryItemResponseDto } from './galleryItemResponseDto';

export interface DiscoveryUserItemDto {
  /** Unique identifier of the user */
  id: string;
  /** Name of the user */
  name: string;
  /** Faculty the user belongs to */
  faculty: DiscoveryUserItemDtoFaculty;
  /**
     * Nationality of the user
     * @nullable
     */
  nationality: DiscoveryUserItemDtoNationality;
  /**
     * Short bio of the user
     * @nullable
     */
  bio: string | null;
  /**
     * Last seen timestamp of the user
     * @nullable
     */
  lastSeen: string | null;
  /** Interests of the user */
  interests: DiscoveryUserItemDtoInterestsItem[];
  /**
     * What the user is looking for
     * @nullable
     */
  lookingFor: DiscoveryUserItemDtoLookingFor;
  /** Gallery images of the user */
  gallery: GalleryItemResponseDto[];
}
