/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type MatchesControllerGetMatchesParams = {
    /**
     * Cursor for pagination (match ID)
     */
    cursor?: string;
    /**
     * Number of matches to return
     * @minimum 1
     * @maximum 50
     */
    limit?: number;
};
