/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface MatchMarkAsSeenResponseDto {
    /** Success message */
    message: string;
    /** ID of the match that was marked as seen */
    matchId: string;
}
