/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { MatchItemDto } from './matchItemDto';

export interface MatchListResponseDto {
    /** List of matches */
    matches: MatchItemDto[];
    /**
     * Cursor for pagination (null if no more matches)
     * @nullable
     */
    nextCursor: string | null;
}
