/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface MessageItemDto {
    /** Message ID */
    id: string;
    /** Message content */
    content: string;
    /** ID of the message sender */
    senderId: string;
    /** Timestamp when the message was sent */
    timestamp: string;
}
