/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface MessageStatsDto {
  /** Total messages */
  total: number;
  /** Total conversations */
  totalConversations: number;
  /** New messages in last 7 days */
  newLast7Days: number;
  /** New messages in last 30 days */
  newLast30Days: number;
}
