/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { MessageItemDto } from './messageItemDto';

export interface MessagesListResponseDto {
  /** List of messages in the conversation */
  messages: MessageItemDto[];
  /**
     * Cursor for pagination (null if no more messages)
     * @nullable
     */
  nextCursor: string | null;
}
