/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Type of the notification
 */
export type NotificationItemDtoType = typeof NotificationItemDtoType[keyof typeof NotificationItemDtoType];


export const NotificationItemDtoType = {
  NEW_MATCH: 'NEW_MATCH',
  NEW_MESSAGE: 'NEW_MESSAGE',
  SHOUTOUT_RECEIVED: 'SHOUTOUT_RECEIVED',
  SHOUTOUT_REPLIED: 'SHOUTOUT_REPLIED',
  SYSTEM: 'SYSTEM',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
} as const;
