/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Additional metadata associated with the notification
 * @nullable
 */
export type NotificationItemDtoData = { [key: string]: unknown } | null;
