/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type NotificationsControllerGetNotificationsParams = {
/**
 * Cursor for pagination (ID of the last item from previous page)
 * @nullable
 */
cursor?: string | null;
/**
 * Number of items to return
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
