/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { NotificationStatsDtoByType } from './notificationStatsDtoByType';

export interface NotificationStatsDto {
  /** Total notifications */
  total: number;
  /** Unread notifications */
  unread: number;
  /** Notifications by type */
  byType: NotificationStatsDtoByType;
}
