/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { NotificationItemDto } from './notificationItemDto';

export interface NotificationsListResponseDto {
  /** List of notifications */
  notifications: NotificationItemDto[];
  /**
     * Cursor for pagination (null if no more notifications)
     * @nullable
     */
  nextCursor: string | null;
}
