/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Preferred gender
 */
export type PrivateProfileResponseDtoPreferredGender = typeof PrivateProfileResponseDtoPreferredGender[keyof typeof PrivateProfileResponseDtoPreferredGender];


export const PrivateProfileResponseDtoPreferredGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  ALL: 'ALL',
} as const;
