/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Gender
 */
export type PrivateProfileResponseDtoGender = (typeof PrivateProfileResponseDtoGender)[keyof typeof PrivateProfileResponseDtoGender];

export const PrivateProfileResponseDtoGender = {
    MALE: 'MALE',
    FEMALE: 'FEMALE',
    OTHER: 'OTHER'
} as const;
