/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { GalleryItemResponseDto } from './galleryItemResponseDto';
import type { PrivateProfileResponseDtoFaculty } from './privateProfileResponseDtoFaculty';
import type { PrivateProfileResponseDtoGender } from './privateProfileResponseDtoGender';
import type { PrivateProfileResponseDtoInterestsItem } from './privateProfileResponseDtoInterestsItem';
import type { PrivateProfileResponseDtoLookingFor } from './privateProfileResponseDtoLookingFor';
import type { PrivateProfileResponseDtoNationality } from './privateProfileResponseDtoNationality';
import type { PrivateProfileResponseDtoPreferredFacultiesItem } from './privateProfileResponseDtoPreferredFacultiesItem';
import type { PrivateProfileResponseDtoPreferredGender } from './privateProfileResponseDtoPreferredGender';
import type { PrivateProfileResponseDtoPreferredNationalitiesItem } from './privateProfileResponseDtoPreferredNationalitiesItem';

export interface PrivateProfileResponseDto {
    /** User ID */
    id: string;
    /** Email */
    email: string;
    /** Name */
    name: string;
    /**
     * Avatar URL
     * @nullable
     */
    avatarUrl: string | null;
    /**
     * Bio
     * @nullable
     */
    bio: string | null;
    /** Gender */
    gender: PrivateProfileResponseDtoGender;
    /**
     * Faculty
     * @nullable
     */
    faculty: PrivateProfileResponseDtoFaculty;
    /**
     * Nationality
     * @nullable
     */
    nationality: PrivateProfileResponseDtoNationality;
    /** List of interests */
    interests: PrivateProfileResponseDtoInterestsItem[];
    /**
     * What the user is looking for
     * @nullable
     */
    lookingFor: PrivateProfileResponseDtoLookingFor;
    /**
     * Birth year
     * @nullable
     */
    birthYear: number | null;
    /**
     * Minimum preferred age
     * @nullable
     */
    minPreferredAge: number | null;
    /**
     * Maximum preferred age
     * @nullable
     */
    maxPreferredAge: number | null;
    /** Preferred gender */
    preferredGender: PrivateProfileResponseDtoPreferredGender;
    /** Preferred nationalities */
    preferredNationalities: PrivateProfileResponseDtoPreferredNationalitiesItem[];
    /** Preferred faculties */
    preferredFaculties: PrivateProfileResponseDtoPreferredFacultiesItem[];
    /** User gallery items */
    gallery: GalleryItemResponseDto[];
    /** Whether the user is discoverable in the feed */
    isDiscoverable: boolean;
}
