/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface ProfileStatus {
    /** Indicates if the user has completed their profile */
    data: boolean;
    /** Indicates if the user has uploaded an avatar */
    avatar: boolean;
    /** Indicates if the user has uploaded gallery items */
    gallery: boolean;
}
