/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { PrivateProfileResponseDto } from './privateProfileResponseDto';
import type { ProfileStatus } from './profileStatus';

export interface ProfileStatusResponseDto {
    /** Success message */
    message: string;
    /** Indicates if the profile is complete */
    isComplete: boolean;
    /** Profile status */
    status: ProfileStatus;
    /** User profile */
    user: PrivateProfileResponseDto;
}
