/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Faculty
 * @nullable
 */
export type PublicUserProfileDtoFaculty = (typeof PublicUserProfileDtoFaculty)[keyof typeof PublicUserProfileDtoFaculty] | null;

export const PublicUserProfileDtoFaculty = {
    THAI: 'THAI',
    ENGLISH: 'ENGLISH',
    DTI: 'DTI',
    HRM: 'HRM',
    BBA: 'BBA',
    CIVIL: 'CIVIL',
    AVIATION: 'AVIATION',
    ENGINEERING: 'ENGINEERING',
    PSYCHOLOGY: 'PSYCHOLOGY',
    LAW: 'LAW',
    COMM_ARTS: 'COMM_ARTS',
    ARCHITECTURE: 'ARCHITECTURE'
} as const;
