/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Gender
 */
export type PublicUserProfileDtoGender = typeof PublicUserProfileDtoGender[keyof typeof PublicUserProfileDtoGender];


export const PublicUserProfileDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;
