/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { ReportItemDto } from './reportItemDto';

export interface ReportsListResponseDto {
    /** List of reports */
    reports: ReportItemDto[];
    /** Total number of reports */
    total: number;
    /** Current page number */
    page: number;
    /** Items per page */
    limit: number;
    /** Total number of pages */
    totalPages: number;
}
