/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Report reason
 */
export type ReportItemDtoReason = (typeof ReportItemDtoReason)[keyof typeof ReportItemDtoReason];

export const ReportItemDtoReason = {
    INAPPROPRIATE_BEHAVIOR: 'INAPPROPRIATE_BEHAVIOR',
    FAKE_PROFILE: 'FAKE_PROFILE',
    SCAM: 'SCAM',
    HARASSMENT: 'HARASSMENT',
    OTHER: 'OTHER'
} as const;
