/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { ReportsControllerResolveReportBodyAction } from './reportsControllerResolveReportBodyAction';

export type ReportsControllerResolveReportBody = {
    action?: ReportsControllerResolveReportBodyAction;
};
