/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type ReportsControllerGetReportsStatus = typeof ReportsControllerGetReportsStatus[keyof typeof ReportsControllerGetReportsStatus];


export const ReportsControllerGetReportsStatus = {
  PENDING: 'PENDING',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED',
} as const;
