/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface ReportChatMessageDto {
  /** Message ID */
  id: string;
  /** Message sender ID */
  senderId: string;
  /** Message receiver ID */
  receiverId: string;
  /** Message content */
  content: string;
  /** Whether the message is read */
  isRead: boolean;
  /** Message creation timestamp */
  createdAt: string;
}
