/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type ReportsControllerResolveReportBodyAction = typeof ReportsControllerResolveReportBodyAction[keyof typeof ReportsControllerResolveReportBodyAction];


export const ReportsControllerResolveReportBodyAction = {
  RESOLVE: 'RESOLVE',
  DISMISS: 'DISMISS',
} as const;
