/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { ReportsControllerGetReportsSortOrder } from './reportsControllerGetReportsSortOrder';
import type { ReportsControllerGetReportsStatus } from './reportsControllerGetReportsStatus';

export type ReportsControllerGetReportsParams = {
    /**
     * Page number for pagination (default: 1)
     * @minimum 1
     */
    page?: number;
    /**
     * Number of items to return per page (default: 20)
     * @minimum 1
     * @maximum 50
     */
    limit?: number;
    /**
     * Sort order for createdAt (default: desc)
     */
    sortOrder?: ReportsControllerGetReportsSortOrder;
    /**
     * Filter by report status
     */
    status?: ReportsControllerGetReportsStatus;
};
