/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { ReportChatMessageDto } from './reportChatMessageDto';
import type { ReportDetailsResponseDtoReason } from './reportDetailsResponseDtoReason';
import type { ReportDetailsResponseDtoStatus } from './reportDetailsResponseDtoStatus';
import type { ReportUserWithBanStatusDto } from './reportUserWithBanStatusDto';

export interface ReportDetailsResponseDto {
    /** Report ID */
    id: string;
    /** Reporter user ID */
    reporterId: string;
    /** Reported user ID */
    reportedId: string;
    /** Report reason */
    reason: ReportDetailsResponseDtoReason;
    /**
     * Report description
     * @nullable
     */
    description: string | null;
    /** Report status */
    status: ReportDetailsResponseDtoStatus;
    /** Report creation timestamp */
    createdAt: string;
    /** Report update timestamp */
    updatedAt: string;
    /** Reporter details */
    reporter: ReportUserWithBanStatusDto;
    /** Reported user details */
    reported: ReportUserWithBanStatusDto;
    /** Recent chat context */
    chatContext: ReportChatMessageDto[];
}
