/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Report status
 */
export type ReportItemDtoStatus = typeof ReportItemDtoStatus[keyof typeof ReportItemDtoStatus];


export const ReportItemDtoStatus = {
  PENDING: 'PENDING',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED',
} as const;
