/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface SendShoutoutDto {
  /** ID of the user to send the shoutout to */
  receiverId: string;
  /** Shoutout message content */
  message: string;
}
