/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { ShoutoutItemDto } from './shoutoutItemDto';

export interface ShoutoutsListResponseDto {
  /** List of shoutouts */
  shoutouts: ShoutoutItemDto[];
  /**
     * Cursor for pagination (null if no more shoutouts)
     * @nullable
     */
  nextCursor: string | null;
}
