/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface ShoutoutStatsDto {
  /** Total shoutouts */
  total: number;
  /** New shoutouts in last 7 days */
  newLast7Days: number;
}
