/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Whether this shoutout was sent or received
 */
export type ShoutoutItemDtoType = (typeof ShoutoutItemDtoType)[keyof typeof ShoutoutItemDtoType];

export const ShoutoutItemDtoType = {
    sent: 'sent',
    received: 'received'
} as const;
