/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { SwipeMatchDto } from './swipeMatchDto';

export interface SwipeResponseDto {
    /** Whether this swipe resulted in a match */
    isMatch: boolean;
    /** Match details (null if no match) */
    match: SwipeMatchDto | null;
}
