/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { UserSummaryDto } from './userSummaryDto';

export interface SwipeMatchDto {
    /** Match ID */
    id: string;
    /** Timestamp when the match was created */
    createdAt: string;
    /** Summary of the matched user */
    matcher: UserSummaryDto;
    /**
     * Conversation ID (null if not yet created)
     * @nullable
     */
    conversationId: string | null;
}
