/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Reason for unmatching
 */
export type UnmatchDtoReason = typeof UnmatchDtoReason[keyof typeof UnmatchDtoReason];


export const UnmatchDtoReason = {
  NOT_INTERESTED: 'NOT_INTERESTED',
  OTHER: 'OTHER',
  ABUSE: 'ABUSE',
  SPAM: 'SPAM',
} as const;
