/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { UnmatchDtoReason } from './unmatchDtoReason';

export interface UnmatchDto {
    /** Reason for unmatching */
    reason: UnmatchDtoReason;
    /** Additional details for unmatching */
    details?: string;
}
