/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface UnmatchResponseDto {
    /** Success message */
    message: string;
    /** ID of the unmatched user */
    userId: string;
    /** ID of the match that was removed */
    matchId: string;
}
