/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface UpdateMessageDto {
  /**
     * Updated message content
     * @minLength 1
     * @maxLength 500
     */
  content: string;
}
