/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { NewGalleryImageDto } from './newGalleryImageDto';
import type { UpdateProfileDtoFaculty } from './updateProfileDtoFaculty';
import type { UpdateProfileDtoGender } from './updateProfileDtoGender';
import type { UpdateProfileDtoInterestsItem } from './updateProfileDtoInterestsItem';
import type { UpdateProfileDtoLookingFor } from './updateProfileDtoLookingFor';
import type { UpdateProfileDtoNationality } from './updateProfileDtoNationality';
import type { UpdateProfileDtoPreferredFacultiesItem } from './updateProfileDtoPreferredFacultiesItem';
import type { UpdateProfileDtoPreferredGender } from './updateProfileDtoPreferredGender';
import type { UpdateProfileDtoPreferredNationalitiesItem } from './updateProfileDtoPreferredNationalitiesItem';

export interface UpdateProfileDto {
  /**
     * User full name
     * @minLength 2
     * @maxLength 100
     */
  name: string;
  /** URL of the user avatar */
  avatarUrl?: string;
  /**
     * User biography
     * @minLength 0
     * @maxLength 500
     */
  bio?: string;
  /** User faculty */
  faculty: UpdateProfileDtoFaculty;
  /** User interests */
  interests: UpdateProfileDtoInterestsItem[];
  /** User gender */
  gender: UpdateProfileDtoGender;
  /**
     * Birth year
     * @minimum 1986
     * @maximum 2008
     */
  birthYear: number;
  /**
     * Minimum preferred age
     * @minimum 18
     * @maximum 99
     */
  minPreferredAge?: number;
  /**
     * Maximum preferred age
     * @minimum 18
     * @maximum 99
     */
  maxPreferredAge?: number;
  /** Preferred gender for matching */
  preferredGender: UpdateProfileDtoPreferredGender;
  /** User nationality */
  nationality?: UpdateProfileDtoNationality;
  /** Preferred nationalities for matching */
  preferredNationalities?: UpdateProfileDtoPreferredNationalitiesItem[];
  /** Preferred faculties for matching */
  preferredFaculties?: UpdateProfileDtoPreferredFacultiesItem[];
  /** What the user is looking for */
  lookingFor?: UpdateProfileDtoLookingFor;
  /**
     * Updated gallery images
     * @minItems 1
     * @maxItems 10
     */
  gallery: NewGalleryImageDto[];
}
