/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { NewGalleryImageDto } from './newGalleryImageDto';
import type { UpdateProfileDtoFaculty } from './updateProfileDtoFaculty';
import type { UpdateProfileDtoGender } from './updateProfileDtoGender';
import type { UpdateProfileDtoInterestsItem } from './updateProfileDtoInterestsItem';
import type { UpdateProfileDtoLookingFor } from './updateProfileDtoLookingFor';
import type { UpdateProfileDtoNationality } from './updateProfileDtoNationality';
import type { UpdateProfileDtoPreferredFacultiesItem } from './updateProfileDtoPreferredFacultiesItem';
import type { UpdateProfileDtoPreferredGender } from './updateProfileDtoPreferredGender';
import type { UpdateProfileDtoPreferredNationalitiesItem } from './updateProfileDtoPreferredNationalitiesItem';

export interface UpdateProfileDto {
    /** User full name */
    name: string;
    /** URL of the user avatar */
    avatarUrl?: string;
    /** User biography */
    bio?: string;
    /** User faculty */
    faculty: UpdateProfileDtoFaculty;
    /** User interests */
    interests: UpdateProfileDtoInterestsItem[];
    /** User gender */
    gender: UpdateProfileDtoGender;
    /** Birth year */
    birthYear: number;
    /** Minimum preferred age */
    minPreferredAge?: number;
    /** Maximum preferred age */
    maxPreferredAge?: number;
    /** Preferred gender for matching */
    preferredGender: UpdateProfileDtoPreferredGender;
    /** User nationality */
    nationality?: UpdateProfileDtoNationality;
    /** Preferred nationalities for matching */
    preferredNationalities?: UpdateProfileDtoPreferredNationalitiesItem[];
    /** Preferred faculties for matching */
    preferredFaculties?: UpdateProfileDtoPreferredFacultiesItem[];
    /** What the user is looking for */
    lookingFor?: UpdateProfileDtoLookingFor;
    /** Updated gallery images */
    gallery: NewGalleryImageDto[];
}
