/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface UpdateAnnouncementDto {
  /**
     * Announcement title
     * @minLength 1
     * @maxLength 200
     */
  title?: string;
  /**
     * Announcement body
     * @minLength 1
     * @maxLength 2000
     */
  body?: string;
}
