/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { UploadedImageItemDto } from './uploadedImageItemDto';

export interface UploadGalleryImagesResponseDto {
  /** List of uploaded images with their URLs and unique keys */
  images: UploadedImageItemDto[];
}
