/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface UploadedImageItemDto {
    /** URL where the uploaded image can be accessed */
    url: string;
    /** Unique identifier for the uploaded image */
    key: string;
}
