/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { UserStatsDtoByFaculty } from './userStatsDtoByFaculty';
import type { UserStatsDtoByGender } from './userStatsDtoByGender';

export interface UserStatsDto {
  /** Total users */
  total: number;
  /** Banned users */
  banned: number;
  /** Admin users */
  admins: number;
  /** Users with completed profiles */
  profileComplete: number;
  /** Users by gender */
  byGender: UserStatsDtoByGender;
  /** Users by faculty */
  byFaculty: UserStatsDtoByFaculty;
  /** New users in last 7 days */
  newLast7Days: number;
  /** New users in last 30 days */
  newLast30Days: number;
}
