/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface VerifyCodeResponseDto {
    /** JWT access token */
    access_token: string;
    /** Token expiration time in seconds */
    expiresIn: number;
    /** Indicates if user profile is completed */
    profileCompleted: boolean;
}
