/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export interface VerifyAdminDto {
  /** The email address of the admin user. */
  email: string;
  /**
     * 6-digit verification code
     * @minLength 6
     * @maxLength 6
     */
  code: string;
}
